# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dabf8cd89d45d3cf0c9bf5bef37a4b8da123f892059d2d199c3402681461919fce0ebf784f95eb6c181160e5cc2fbf3fc0db77404886ae41ec1741e3d1ec338

test:
  secret_key_base: 7b81750b31803026f419542f9f6aa9130d35a67cf961eb0b95bfb17b8632da03b52cf037ce4a23e0cb732d40f9c5beb7ef1137438a769bad2d2e9c2dfe38cad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
